
donation-message: [
  " &f&l** &6%player% &ehas just purchased &6Something&e! &f&l**",
  "   &f&l** &eThank you for your kind donation! &f&l**",
  "&r",
  "&r",
  "&r",
  "&r",
  "&r",
  "  &7&o(( Donations help keep the network alive! ))"
]